ARG BASE_FDB_IMAGE=openaiapibase.azurecr.io/mirror/foundationdb/foundationdb:7.3.69
ARG EXTRA_FDB_LIBRARY_IMAGE=openaiapibase.azurecr.io/mirror/foundationdb/foundationdb:7.4.3

FROM ${EXTRA_FDB_LIBRARY_IMAGE} AS fdb7.4
FROM ${BASE_FDB_IMAGE} AS fdb7.3
FROM openaiapibase.azurecr.io/mirror/foundationdb/rockylinux9-latest@sha256:27e84fcd4a82e63b1f499cf199c84fe9a1831c8858947b3d9e0434b22317075a AS base

ARG BASE_FDB_MINOR_VERSION=7.3

RUN mkdir -p /usr/lib/fdb/multiversion /var/log/fdb-trace-logs /var/fdb
COPY --from=fdb7.4 /usr/lib/fdb/multiversion/libfdb_c_*.so /usr/lib/fdb/multiversion/
COPY --from=fdb7.3 /usr/lib/fdb/multiversion/libfdb_c_*.so /usr/lib/fdb/multiversion/
COPY libfdb_c.so /usr/lib/fdb/multiversion/libfdb_c_${BASE_FDB_MINOR_VERSION}.so
COPY libfdb_c.so /usr/lib/

COPY --chmod=0755 backup_agent /usr/bin/fdbbackup
COPY --chmod=0755 backup_agent /usr/bin/backup_agent
COPY --chmod=0755 fdbcli /usr/bin/fdbcli
ENV FDB_CLUSTER_FILE=/var/fdb/fdb.cluster
ENV FDB_NETWORK_OPTION_EXTERNAL_CLIENT_DIRECTORY=/usr/lib/fdb/multiversion
ENV FDB_NETWORK_OPTION_TRACE_ENABLE=/var/log/fdb-trace-logs
