# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: joshua_proxy.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12joshua_proxy.proto\x12\x1copenai.fdbci.joshua_proxy.v1\"A\n\x10SubmitJobRequest\x12\x1f\n\x17\x63orrectness_package_url\x18\x01 \x01(\t\x12\x0c\n\x04runs\x18\x02 \x01(\x04\" \n\x0eSubmitJobReply\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"%\n\x13GetJobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\x9e\x02\n\x11GetJobStatusReply\x12\x15\n\rjoshua_job_id\x18\x01 \x01(\t\x12\x38\n\x07success\x18\x02 \x01(\x0b\x32%.openai.fdbci.joshua_proxy.v1.SuccessH\x00\x12<\n\tcancelled\x18\x03 \x01(\x0b\x32\'.openai.fdbci.joshua_proxy.v1.CancelledH\x00\x12\x38\n\x07running\x18\x04 \x01(\x0b\x32%.openai.fdbci.joshua_proxy.v1.RunningH\x00\x12\x36\n\x06\x66\x61iled\x18\x05 \x01(\x0b\x32$.openai.fdbci.joshua_proxy.v1.FailedH\x00\x42\x08\n\x06status\"\x1f\n\x07Success\x12\x14\n\x0ctests_passed\x18\x01 \x01(\x04\":\n\tCancelled\x12\x14\n\x0ctests_passed\x18\x01 \x01(\x04\x12\x17\n\x0ftests_remaining\x18\x02 \x01(\x04\"8\n\x07Running\x12\x14\n\x0ctests_passed\x18\x01 \x01(\x04\x12\x17\n\x0ftests_remaining\x18\x02 \x01(\x04\"[\n\x06\x46\x61iled\x12\x14\n\x0ctests_passed\x18\x01 \x01(\x04\x12;\n\x08\x66\x61ilures\x18\x02 \x03(\x0b\x32).openai.fdbci.joshua_proxy.v1.TestFailure\".\n\x0bTestFailure\x12\x11\n\ttest_name\x18\x01 \x01(\t\x12\x0c\n\x04seed\x18\x02 \x01(\x04\x32\xec\x01\n\x0bJoshuaProxy\x12i\n\tSubmitJob\x12..openai.fdbci.joshua_proxy.v1.SubmitJobRequest\x1a,.openai.fdbci.joshua_proxy.v1.SubmitJobReply\x12r\n\x0cGetJobStatus\x12\x31.openai.fdbci.joshua_proxy.v1.GetJobStatusRequest\x1a/.openai.fdbci.joshua_proxy.v1.GetJobStatusReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'joshua_proxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITJOBREQUEST']._serialized_start=52
  _globals['_SUBMITJOBREQUEST']._serialized_end=117
  _globals['_SUBMITJOBREPLY']._serialized_start=119
  _globals['_SUBMITJOBREPLY']._serialized_end=151
  _globals['_GETJOBSTATUSREQUEST']._serialized_start=153
  _globals['_GETJOBSTATUSREQUEST']._serialized_end=190
  _globals['_GETJOBSTATUSREPLY']._serialized_start=193
  _globals['_GETJOBSTATUSREPLY']._serialized_end=479
  _globals['_SUCCESS']._serialized_start=481
  _globals['_SUCCESS']._serialized_end=512
  _globals['_CANCELLED']._serialized_start=514
  _globals['_CANCELLED']._serialized_end=572
  _globals['_RUNNING']._serialized_start=574
  _globals['_RUNNING']._serialized_end=630
  _globals['_FAILED']._serialized_start=632
  _globals['_FAILED']._serialized_end=723
  _globals['_TESTFAILURE']._serialized_start=725
  _globals['_TESTFAILURE']._serialized_end=771
  _globals['_JOSHUAPROXY']._serialized_start=774
  _globals['_JOSHUAPROXY']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
