steps:
  - label: ":hammer: General build"
    key: "general-build"
    agents:
      queue: "applied-bk-agent-fdb"
    command: "bash building/buildkite/general_build.sh"
    artifact_paths:
      - ".buildkite-artifacts/correctness.tar.gz"
      - ".buildkite-artifacts/sccache-stats.txt"

  - label: ":test_tube: Submit Joshua job"
    key: "submit-joshua"
    agents:
      queue: "applied-bk-agent-fdb"
    depends_on: "general-build"
    command: "bash building/buildkite/submit_joshua.sh"
